--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/dropmebeat/WorldBorderBedrock-PocketMine
build-by-default: true
branches:
- main
projects:
  WorldBorderBedrock-PocketMine:
    path: ""
...
